# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7170166141bad6e8a0e1b05ffb9f459a0014bf1d1e52c6f48b15ee51ee5ceea6e6b63e7cba685ca198b16968bb908b7e41e1228ef462ca1c6304b34ebe036b3f

test:
  secret_key_base: 44f73dce8bb11c3c2be3a3c392f189d898082067ba1aeb44746963c8472bd7474997bc74a1caa131fb6d36ef433c43201c702abd2a8ad3144172ead605712387

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
